### ISSUE TITLE
Failed to find time zone: EST

### ISSUE THREAD

**Issue by ghost** [dhasenan/datefmt#1]
Example code fails with Windows and dmd-v2.077.1

`import std.stdio;
import std.datetime;

void main()
{
    import datefmt;
    auto st = SysTime(DateTime(2014, 4, 17, 14, 47, 35), UTC());
    writefln(st.format("%a, %d %b %Y %H:%M:%S GMT"));
}`

dub run
core.time.TimeException@std\datetime\timezone.d(2969): Failed to find time zone: EST
Program exited with code 1

**Comment by dhasenan** [comment]
I don't suppose you could just not use Windows?

...all right, I'll take a look.

**Comment by dhasenan** [comment]
I checked my fix under Wine and the tests currently pass. I don't have access to a Windows computer, so I can't tell for certain if it's going to work on Windows.
