### ISSUE TITLE
GDC Compile fail

### ISSUE THREAD

**Issue by yatima1460** [dhasenan/datefmt#2]
Decided to add Travis CI to my project and found out datefmt builds with DMD and LDC but with GDC it fails, ideas why?
Is GDC still incomplete?

> datefmt.d:439:17: error: template core.time.Duration.opCast does not match any template declaration
>                  tzOffset ? new immutable SimpleTimeZone(tzOffset) : *tz);

gdc (gdcproject.org 20161225-v2.068.2_gcc4.8) 4.8.5

**Comment by dhasenan** [comment]
Fixed with 1.0.3. Thanks for the report!

GDC uses a DMD frontend and standard library from 2015, and that opCast apparently wasn't present in the standard library at that time. Incidentally, it was an error on my part to use that opCast in the first place, and that has been corrected.
